"""Task state management for MAS-style scheduling."""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class AgentResult:
    """Structured output returned by every worker agent.
    
    Fields:
        name: Agent name/role
        summary: Brief summary of what the agent did (generated by Memer)
        raw_output: Full structured output from the agent
        control: Control signals (e.g., task_complete, need_more_search)
    """
    name: str
    summary: str
    raw_output: Dict[str, Any]
    control: Dict[str, Any]


@dataclass
class MemoryFeedback:
    """Feedback from agent about routed memories usefulness.
    
    This is used to compute hit rate h_{i,t} for Router reward:
    h_{i,t} = useful_count / routed_count
    """
    routed_count: int = 0     # k_{i,t}: Number of memories routed to agent
    useful_count: int = 0     # u_{i,t}: Number marked useful by agent
    
    @property
    def hit_rate(self) -> float:
        """Compute h_{i,t} = u_{i,t} / k_{i,t}."""
        if self.routed_count == 0:
            return 0.0
        return self.useful_count / self.routed_count


@dataclass
class StepMetrics:
    """Metrics collected at each step for reward calculation."""
    step_idx: int = 0                     # t (1-indexed)
    
    # Scheduler decision
    scheduler_action: str = ""            # Agent name chosen
    scheduler_log_prob: float = 0.0       # log π(a|s) for scheduler
    scheduler_prompt: str = ""            # Full prompt used
    
    # Router decision
    router_action: List[int] = field(default_factory=list)  # Memory indices selected
    router_log_prob: float = 0.0          # log π(a|s) for router
    router_prompt: str = ""               # Full prompt used
    
    # Memory feedback (from agent)
    memory_feedback: MemoryFeedback = field(default_factory=MemoryFeedback)
    
    # Token consumption
    token_count: int = 0                  # c_{i,t}: Tokens consumed this step


@dataclass
class HistoryEntry:
    """Records execution history for each step."""
    agent: str
    summary: str  # Generated by Memer
    raw_output: Dict[str, Any]
    control: Dict[str, Any]
    metrics: Optional[StepMetrics] = None  # Metrics for training


class MASTaskState:
    """Keeps track of execution status for a single task.
    
    This is the central state object that Scheduler and Router use
    to make decisions about agent selection and memory routing.
    
    Extended to support RL training:
    - Tracks step metrics (scheduler/router decisions, log probs)
    - Collects memory feedback from agents for router hit rate
    - Records token consumption for scheduler cost
    """
    
    def __init__(self, task: Dict[str, Any]):
        self.task = task
        self.task_id: str = str(task.get("id", "unknown"))
        self.steps: int = 0
        self.finished: bool = False
        self.final_answer: Optional[str] = None
        
        # Intermediate results
        self.collected_evidence: List[Dict[str, Any]] = []
        self.reasoning_results: List[str] = []
        
        # Memory state
        self.pre_agent: Optional[str] = None
        self.pre_mem: str = ""
        self.sum_memory: str = ""
        
        # Full history
        self.history: List[HistoryEntry] = []
        
        # Answers collected from agents
        self.answers: List[str] = []
        
        # RL training: step metrics (parallel to history)
        self.step_metrics: List[StepMetrics] = []
        self._current_step_metrics: Optional[StepMetrics] = None
        
        # Task reward (set after evaluation)
        self.task_reward: float = 0.0
        self.total_tokens: int = 0
    
    def begin_step(self) -> StepMetrics:
        """Begin a new step, creating fresh metrics to record."""
        self._current_step_metrics = StepMetrics(step_idx=self.steps + 1)
        return self._current_step_metrics
    
    def record_scheduler_decision(
        self,
        action: str,
        log_prob: float = 0.0,
        prompt: str = "",
    ):
        """Record scheduler's decision for this step."""
        if self._current_step_metrics is None:
            self.begin_step()
        self._current_step_metrics.scheduler_action = action
        self._current_step_metrics.scheduler_log_prob = log_prob
        self._current_step_metrics.scheduler_prompt = prompt
    
    def record_router_decision(
        self,
        action: List[int],
        log_prob: float = 0.0,
        prompt: str = "",
        routed_count: int = 0,
    ):
        """Record router's decision for this step."""
        if self._current_step_metrics is None:
            self.begin_step()
        self._current_step_metrics.router_action = action
        self._current_step_metrics.router_log_prob = log_prob
        self._current_step_metrics.router_prompt = prompt
        self._current_step_metrics.memory_feedback.routed_count = routed_count
    
    def record_agent_feedback(self, useful_count: int):
        """
        Record agent's feedback on how many routed memories were useful.
        
        This is called by the work agent after it processes routed memories.
        The agent reports how many of the routed memories were actually useful.
        
        Args:
            useful_count: Number of memories the agent found useful (u_{i,t})
        """
        if self._current_step_metrics is None:
            return
        self._current_step_metrics.memory_feedback.useful_count = useful_count
    
    def record_token_count(self, tokens: int):
        """Record token consumption for this step."""
        if self._current_step_metrics is None:
            self.begin_step()
        self._current_step_metrics.token_count = tokens
        self.total_tokens += tokens
    
    def register_step(
        self,
        result: AgentResult,
        memer_summary: str,
        sum_memory: str,
    ) -> None:
        """Update state after an agent finishes its work.
        
        Args:
            result: Worker agent's output
            memer_summary: Summary generated by Memer
            sum_memory: Global progress summary
        """
        self.steps += 1
        self.pre_agent = result.name
        self.pre_mem = memer_summary
        self.sum_memory = sum_memory
        
        # Finalize current step metrics
        metrics = self._current_step_metrics
        self._current_step_metrics = None
        
        # Save to history
        self.history.append(HistoryEntry(
            agent=result.name,
            summary=memer_summary,
            raw_output=result.raw_output,
            control=result.control,
            metrics=metrics,
        ))
        
        # Also save metrics to flat list for easy access
        if metrics is not None:
            self.step_metrics.append(metrics)
        
        # Extract specific outputs
        if "answer" in result.raw_output and result.raw_output["answer"]:
            self.answers.append(result.raw_output["answer"])
        
        if "final_answer" in result.raw_output:
            self.final_answer = result.raw_output["final_answer"]
        
        if "reasoning" in result.raw_output:
            self.reasoning_results.append(result.raw_output["reasoning"])
        
        # Check control signals
        if result.control.get("task_complete"):
            self.finished = True
        if result.control.get("terminated"):
            self.finished = True
    
    def set_task_reward(self, reward: float):
        """Set the final task reward from evaluator."""
        self.task_reward = reward
    
    def to_scheduler_view(self, agent_specs: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generate the view that Scheduler sees.
        
        Scheduler inputs:
        - task: The full task object
        - pre_mem: Last step's memory summary
        - pre_agent: Last agent that worked
        - sum_memory: Global progress summary
        - agent_specs: Available agents and their capabilities
        """
        return {
            "task": self.task,
            "pre_mem": self.pre_mem,
            "pre_agent": self.pre_agent,
            "sum_memory": self.sum_memory,
            "agent_specs": agent_specs,
        }
    
    def to_router_view(self, now_agent: str) -> Dict[str, Any]:
        """
        Generate the view that Router sees.
        
        Router inputs:
        - task: The full task object
        - now_agent: Currently selected agent
        - sum_memory: Global progress summary
        - pre_agent: Last agent that worked (for context)
        - pre_mem: Last step's memory summary (for context)
        """
        return {
            "task": self.task,
            "now_agent": now_agent,
            "sum_memory": self.sum_memory,
            "pre_agent": self.pre_agent,
            "pre_mem": self.pre_mem,
        }
    
    def get_last_n_summaries(self, n: int = 3) -> List[str]:
        """Get the last N step summaries for context."""
        return [h.summary for h in self.history[-n:]]
    
    def get_agent_sequence(self) -> List[str]:
        """Get the sequence of agents that have acted."""
        return [h.agent for h in self.history]

